spring.application.name=weather-comparison

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.sql.init.mode=always
logging.level.org.springframework.jdbc.core=TRACE
